apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secret-store
  namespace: {{ .Release.Namespace }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.region | default "eu-central-1" }}
      auth:
        secretRef:
          accessKeyIDSecretRef:
            name: eso-aws-creds
            key: accessKeyID
          secretAccessKeySecretRef:
            name: eso-aws-creds
            key: secretAccessKey